(*****************************************)
(*      This file is autogenerated       *)
(*   Any manual changes will be LOST!    *)
(*****************************************)
(* Generated 08.03.2026 12:00:00         *)
(*****************************************)
(* Step 5: Extended model with           *)
(*   - Customer inheritance              *)
(*     (Company / PrivatePerson)         *)
(*   - VATRate lookup class              *)
(*   - VATAmount on InvoiceItem          *)
(*****************************************)

unit InvoiceClasses;

{$INCLUDE Bold.inc}
{$DEFINE InvoiceClasses_unitheader}
{$INCLUDE InvoiceClasses_Interface.inc}

const
  BoldMemberAssertInvalidObjectType: string = 'Object of singlelink (%s.%s) is of wrong type (is %s, should be %s)';

{ TInvoiceClassesRoot }

procedure TInvoiceClassesRootList.Add(NewObject: TInvoiceClassesRoot);
begin
  if Assigned(NewObject) then
    AddElement(NewObject);
end;

function TInvoiceClassesRootList.IndexOf(anObject: TInvoiceClassesRoot): Integer;
begin
  result := IndexOfElement(anObject);
end;

function TInvoiceClassesRootList.Includes(anObject: TInvoiceClassesRoot) : Boolean;
begin
  result := IncludesElement(anObject);
end;

function TInvoiceClassesRootList.AddNew: TInvoiceClassesRoot;
begin
  result := TInvoiceClassesRoot(InternalAddNew);
end;

procedure TInvoiceClassesRootList.Insert(index: Integer; NewObject: TInvoiceClassesRoot);
begin
  if assigned(NewObject) then
    InsertElement(index, NewObject);
end;

function TInvoiceClassesRootList.GetBoldObject(index: Integer): TInvoiceClassesRoot;
begin
  result := TInvoiceClassesRoot(GetElement(index));
end;

procedure TInvoiceClassesRootList.SetBoldObject(index: Integer; NewObject: TInvoiceClassesRoot);
begin;
  SetElement(index, NewObject);
end;

{$IFDEF UseBoldListEnumerator}
function TInvoiceClassesRootList.GetEnumerator: TInvoiceClassesRootListEnumerator;
begin
 Result := TInvoiceClassesRootListEnumerator.Create(Self);
end;

function TInvoiceClassesRootListEnumerator.GetCurrent: TInvoiceClassesRoot;
begin
 Result := List[Index] as TInvoiceClassesRoot;
end;

{$ENDIF UseBoldListEnumerator}

{ TCustomer }

function TCustomer._Get_M_Name: TBAString;
begin
  assert(ValidateMember('TCustomer', 'Name', 0, TBAString));
  Result := TBAString(BoldMembers[0]);
end;

function TCustomer._GetName: String;
begin
  Result := M_Name.AsString;
end;

procedure TCustomer._SetName(const NewValue: String);
begin
  M_Name.AsString := NewValue;
end;

function TCustomer._Get_M_Address: TBAString;
begin
  assert(ValidateMember('TCustomer', 'Address', 1, TBAString));
  Result := TBAString(BoldMembers[1]);
end;

function TCustomer._GetAddress: String;
begin
  Result := M_Address.AsString;
end;

procedure TCustomer._SetAddress(const NewValue: String);
begin
  M_Address.AsString := NewValue;
end;

function TCustomer._Get_M_PostAddress: TBAString;
begin
  assert(ValidateMember('TCustomer', 'PostAddress', 2, TBAString));
  Result := TBAString(BoldMembers[2]);
end;

function TCustomer._GetPostAddress: String;
begin
  Result := M_PostAddress.AsString;
end;

procedure TCustomer._SetPostAddress(const NewValue: String);
begin
  M_PostAddress.AsString := NewValue;
end;

function TCustomer._Get_M_City: TBAString;
begin
  assert(ValidateMember('TCustomer', 'City', 3, TBAString));
  Result := TBAString(BoldMembers[3]);
end;

function TCustomer._GetCity: String;
begin
  Result := M_City.AsString;
end;

procedure TCustomer._SetCity(const NewValue: String);
begin
  M_City.AsString := NewValue;
end;

function TCustomer._Get_M_Country: TBAString;
begin
  assert(ValidateMember('TCustomer', 'Country', 4, TBAString));
  Result := TBAString(BoldMembers[4]);
end;

function TCustomer._GetCountry: String;
begin
  Result := M_Country.AsString;
end;

procedure TCustomer._SetCountry(const NewValue: String);
begin
  M_Country.AsString := NewValue;
end;

function TCustomer._GetInvoices: TInvoiceList;
begin
  assert(ValidateMember('TCustomer', 'Invoices', 5, TInvoiceList));
  Result := TInvoiceList(BoldMembers[5]);
end;

procedure TCustomerList.Add(NewObject: TCustomer);
begin
  if Assigned(NewObject) then
    AddElement(NewObject);
end;

function TCustomerList.IndexOf(anObject: TCustomer): Integer;
begin
  result := IndexOfElement(anObject);
end;

function TCustomerList.Includes(anObject: TCustomer) : Boolean;
begin
  result := IncludesElement(anObject);
end;

function TCustomerList.AddNew: TCustomer;
begin
  result := TCustomer(InternalAddNew);
end;

procedure TCustomerList.Insert(index: Integer; NewObject: TCustomer);
begin
  if assigned(NewObject) then
    InsertElement(index, NewObject);
end;

function TCustomerList.GetBoldObject(index: Integer): TCustomer;
begin
  result := TCustomer(GetElement(index));
end;

procedure TCustomerList.SetBoldObject(index: Integer; NewObject: TCustomer);
begin;
  SetElement(index, NewObject);
end;

{$IFDEF UseBoldListEnumerator}
function TCustomerList.GetEnumerator: TCustomerListEnumerator;
begin
 Result := TCustomerListEnumerator.Create(Self);
end;

function TCustomerListEnumerator.GetCurrent: TCustomer;
begin
 Result := List[Index] as TCustomer;
end;

{$ENDIF UseBoldListEnumerator}

{ TCompany }

function TCompany._Get_M_VATNumber: TBAString;
begin
  assert(ValidateMember('TCompany', 'VATNumber', 6, TBAString));
  Result := TBAString(BoldMembers[6]);
end;

function TCompany._GetVATNumber: String;
begin
  Result := M_VATNumber.AsString;
end;

procedure TCompany._SetVATNumber(const NewValue: String);
begin
  M_VATNumber.AsString := NewValue;
end;

function TCompany._Get_M_VATExempt: TBABoolean;
begin
  assert(ValidateMember('TCompany', 'VATExempt', 7, TBABoolean));
  Result := TBABoolean(BoldMembers[7]);
end;

function TCompany._GetVATExempt: Boolean;
begin
  Result := M_VATExempt.AsBoolean;
end;

procedure TCompany._SetVATExempt(const NewValue: Boolean);
begin
  M_VATExempt.AsBoolean := NewValue;
end;

procedure TCompanyList.Add(NewObject: TCompany);
begin
  if Assigned(NewObject) then
    AddElement(NewObject);
end;

function TCompanyList.IndexOf(anObject: TCompany): Integer;
begin
  result := IndexOfElement(anObject);
end;

function TCompanyList.Includes(anObject: TCompany) : Boolean;
begin
  result := IncludesElement(anObject);
end;

function TCompanyList.AddNew: TCompany;
begin
  result := TCompany(InternalAddNew);
end;

procedure TCompanyList.Insert(index: Integer; NewObject: TCompany);
begin
  if assigned(NewObject) then
    InsertElement(index, NewObject);
end;

function TCompanyList.GetBoldObject(index: Integer): TCompany;
begin
  result := TCompany(GetElement(index));
end;

procedure TCompanyList.SetBoldObject(index: Integer; NewObject: TCompany);
begin;
  SetElement(index, NewObject);
end;

{$IFDEF UseBoldListEnumerator}
function TCompanyList.GetEnumerator: TCompanyListEnumerator;
begin
 Result := TCompanyListEnumerator.Create(Self);
end;

function TCompanyListEnumerator.GetCurrent: TCompany;
begin
 Result := List[Index] as TCompany;
end;

{$ENDIF UseBoldListEnumerator}

{ TPrivatePerson }

{ No own accessors - TPrivatePerson inherits all members from TCustomer }

procedure TPrivatePersonList.Add(NewObject: TPrivatePerson);
begin
  if Assigned(NewObject) then
    AddElement(NewObject);
end;

function TPrivatePersonList.IndexOf(anObject: TPrivatePerson): Integer;
begin
  result := IndexOfElement(anObject);
end;

function TPrivatePersonList.Includes(anObject: TPrivatePerson) : Boolean;
begin
  result := IncludesElement(anObject);
end;

function TPrivatePersonList.AddNew: TPrivatePerson;
begin
  result := TPrivatePerson(InternalAddNew);
end;

procedure TPrivatePersonList.Insert(index: Integer; NewObject: TPrivatePerson);
begin
  if assigned(NewObject) then
    InsertElement(index, NewObject);
end;

function TPrivatePersonList.GetBoldObject(index: Integer): TPrivatePerson;
begin
  result := TPrivatePerson(GetElement(index));
end;

procedure TPrivatePersonList.SetBoldObject(index: Integer; NewObject: TPrivatePerson);
begin;
  SetElement(index, NewObject);
end;

{$IFDEF UseBoldListEnumerator}
function TPrivatePersonList.GetEnumerator: TPrivatePersonListEnumerator;
begin
 Result := TPrivatePersonListEnumerator.Create(Self);
end;

function TPrivatePersonListEnumerator.GetCurrent: TPrivatePerson;
begin
 Result := List[Index] as TPrivatePerson;
end;

{$ENDIF UseBoldListEnumerator}

{ TVATRate }

function TVATRate._Get_M_Name: TBAString;
begin
  assert(ValidateMember('TVATRate', 'Name', 0, TBAString));
  Result := TBAString(BoldMembers[0]);
end;

function TVATRate._GetName: String;
begin
  Result := M_Name.AsString;
end;

procedure TVATRate._SetName(const NewValue: String);
begin
  M_Name.AsString := NewValue;
end;

function TVATRate._Get_M_Percentage: TBAFloat;
begin
  assert(ValidateMember('TVATRate', 'Percentage', 1, TBAFloat));
  Result := TBAFloat(BoldMembers[1]);
end;

function TVATRate._GetPercentage: Double;
begin
  Result := M_Percentage.AsFloat;
end;

procedure TVATRate._SetPercentage(const NewValue: Double);
begin
  M_Percentage.AsFloat := NewValue;
end;

procedure TVATRateList.Add(NewObject: TVATRate);
begin
  if Assigned(NewObject) then
    AddElement(NewObject);
end;

function TVATRateList.IndexOf(anObject: TVATRate): Integer;
begin
  result := IndexOfElement(anObject);
end;

function TVATRateList.Includes(anObject: TVATRate) : Boolean;
begin
  result := IncludesElement(anObject);
end;

function TVATRateList.AddNew: TVATRate;
begin
  result := TVATRate(InternalAddNew);
end;

procedure TVATRateList.Insert(index: Integer; NewObject: TVATRate);
begin
  if assigned(NewObject) then
    InsertElement(index, NewObject);
end;

function TVATRateList.GetBoldObject(index: Integer): TVATRate;
begin
  result := TVATRate(GetElement(index));
end;

procedure TVATRateList.SetBoldObject(index: Integer; NewObject: TVATRate);
begin;
  SetElement(index, NewObject);
end;

{$IFDEF UseBoldListEnumerator}
function TVATRateList.GetEnumerator: TVATRateListEnumerator;
begin
 Result := TVATRateListEnumerator.Create(Self);
end;

function TVATRateListEnumerator.GetCurrent: TVATRate;
begin
 Result := List[Index] as TVATRate;
end;

{$ENDIF UseBoldListEnumerator}

{ TInvoice }

function TInvoice._Get_M_InvoiceNumber: TBAInteger;
begin
  assert(ValidateMember('TInvoice', 'InvoiceNumber', 0, TBAInteger));
  Result := TBAInteger(BoldMembers[0]);
end;

function TInvoice._GetInvoiceNumber: Integer;
begin
  Result := M_InvoiceNumber.AsInteger;
end;

procedure TInvoice._SetInvoiceNumber(const NewValue: Integer);
begin
  M_InvoiceNumber.AsInteger := NewValue;
end;

function TInvoice._Get_M_InvoiceDate: TBADate;
begin
  assert(ValidateMember('TInvoice', 'InvoiceDate', 1, TBADate));
  Result := TBADate(BoldMembers[1]);
end;

function TInvoice._GetInvoiceDate: TDate;
begin
  Result := M_InvoiceDate.AsDate;
end;

procedure TInvoice._SetInvoiceDate(const NewValue: TDate);
begin
  M_InvoiceDate.AsDate := NewValue;
end;

function TInvoice._Get_M_DueDate: TBADate;
begin
  assert(ValidateMember('TInvoice', 'DueDate', 2, TBADate));
  Result := TBADate(BoldMembers[2]);
end;

function TInvoice._GetDueDate: TDate;
begin
  Result := M_DueDate.AsDate;
end;

procedure TInvoice._SetDueDate(const NewValue: TDate);
begin
  M_DueDate.AsDate := NewValue;
end;

function TInvoice._Get_M_IsPaid: TBABoolean;
begin
  assert(ValidateMember('TInvoice', 'IsPaid', 3, TBABoolean));
  Result := TBABoolean(BoldMembers[3]);
end;

function TInvoice._GetIsPaid: Boolean;
begin
  Result := M_IsPaid.AsBoolean;
end;

procedure TInvoice._SetIsPaid(const NewValue: Boolean);
begin
  M_IsPaid.AsBoolean := NewValue;
end;

function TInvoice._Get_M_TotalAmount: TBACurrency;
begin
  assert(ValidateMember('TInvoice', 'TotalAmount', 4, TBACurrency));
  Result := TBACurrency(BoldMembers[4]);
end;

function TInvoice._GetTotalAmount: Currency;
begin
  Result := M_TotalAmount.AsCurrency;
end;

function TInvoice._Get_M_Customer: TBoldObjectReference;
begin
  assert(ValidateMember('TInvoice', 'Customer', 5, TBoldObjectReference));
  Result := TBoldObjectReference(BoldMembers[5]);
end;

function TInvoice._GetCustomer: TCustomer;
begin
  Result := TCustomer(M_Customer.BoldObject);
  if (assigned(Result) and not (Result is TCustomer)) then
    Assert(false, SysUtils.format(BoldMemberAssertInvalidObjectType, [ClassName, 'Customer', Result.ClassName, 'TCustomer']));
end;

procedure TInvoice._SetCustomer(const value: TCustomer);
begin
  M_Customer.BoldObject := value;
end;

function TInvoice._GetItems: TInvoiceItemList;
begin
  assert(ValidateMember('TInvoice', 'Items', 6, TInvoiceItemList));
  Result := TInvoiceItemList(BoldMembers[6]);
end;

procedure TInvoiceList.Add(NewObject: TInvoice);
begin
  if Assigned(NewObject) then
    AddElement(NewObject);
end;

function TInvoiceList.IndexOf(anObject: TInvoice): Integer;
begin
  result := IndexOfElement(anObject);
end;

function TInvoiceList.Includes(anObject: TInvoice) : Boolean;
begin
  result := IncludesElement(anObject);
end;

function TInvoiceList.AddNew: TInvoice;
begin
  result := TInvoice(InternalAddNew);
end;

procedure TInvoiceList.Insert(index: Integer; NewObject: TInvoice);
begin
  if assigned(NewObject) then
    InsertElement(index, NewObject);
end;

function TInvoiceList.GetBoldObject(index: Integer): TInvoice;
begin
  result := TInvoice(GetElement(index));
end;

procedure TInvoiceList.SetBoldObject(index: Integer; NewObject: TInvoice);
begin;
  SetElement(index, NewObject);
end;

{$IFDEF UseBoldListEnumerator}
function TInvoiceList.GetEnumerator: TInvoiceListEnumerator;
begin
 Result := TInvoiceListEnumerator.Create(Self);
end;

function TInvoiceListEnumerator.GetCurrent: TInvoice;
begin
 Result := List[Index] as TInvoice;
end;

{$ENDIF UseBoldListEnumerator}

{ TInvoiceItem }

function TInvoiceItem._Get_M_Description: TBAString;
begin
  assert(ValidateMember('TInvoiceItem', 'Description', 0, TBAString));
  Result := TBAString(BoldMembers[0]);
end;

function TInvoiceItem._GetDescription: String;
begin
  Result := M_Description.AsString;
end;

procedure TInvoiceItem._SetDescription(const NewValue: String);
begin
  M_Description.AsString := NewValue;
end;

function TInvoiceItem._Get_M_Quantity: TBAInteger;
begin
  assert(ValidateMember('TInvoiceItem', 'Quantity', 1, TBAInteger));
  Result := TBAInteger(BoldMembers[1]);
end;

function TInvoiceItem._GetQuantity: Integer;
begin
  Result := M_Quantity.AsInteger;
end;

procedure TInvoiceItem._SetQuantity(const NewValue: Integer);
begin
  M_Quantity.AsInteger := NewValue;
end;

function TInvoiceItem._Get_M_UnitPrice: TBACurrency;
begin
  assert(ValidateMember('TInvoiceItem', 'UnitPrice', 2, TBACurrency));
  Result := TBACurrency(BoldMembers[2]);
end;

function TInvoiceItem._GetUnitPrice: Currency;
begin
  Result := M_UnitPrice.AsCurrency;
end;

procedure TInvoiceItem._SetUnitPrice(const NewValue: Currency);
begin
  M_UnitPrice.AsCurrency := NewValue;
end;

function TInvoiceItem._Get_M_LineTotal: TBACurrency;
begin
  assert(ValidateMember('TInvoiceItem', 'LineTotal', 3, TBACurrency));
  Result := TBACurrency(BoldMembers[3]);
end;

function TInvoiceItem._GetLineTotal: Currency;
begin
  Result := M_LineTotal.AsCurrency;
end;

function TInvoiceItem._Get_M_VATAmount: TBACurrency;
begin
  assert(ValidateMember('TInvoiceItem', 'VATAmount', 4, TBACurrency));
  Result := TBACurrency(BoldMembers[4]);
end;

function TInvoiceItem._GetVATAmount: Currency;
begin
  Result := M_VATAmount.AsCurrency;
end;

function TInvoiceItem._Get_M_Invoice: TBoldObjectReference;
begin
  assert(ValidateMember('TInvoiceItem', 'Invoice', 5, TBoldObjectReference));
  Result := TBoldObjectReference(BoldMembers[5]);
end;

function TInvoiceItem._GetInvoice: TInvoice;
begin
  Result := TInvoice(M_Invoice.BoldObject);
  if (assigned(Result) and not (Result is TInvoice)) then
    Assert(false, SysUtils.format(BoldMemberAssertInvalidObjectType, [ClassName, 'Invoice', Result.ClassName, 'TInvoice']));
end;

procedure TInvoiceItem._SetInvoice(const value: TInvoice);
begin
  M_Invoice.BoldObject := value;
end;

function TInvoiceItem._Get_M_VATRate: TBoldObjectReference;
begin
  assert(ValidateMember('TInvoiceItem', 'VATRate', 6, TBoldObjectReference));
  Result := TBoldObjectReference(BoldMembers[6]);
end;

function TInvoiceItem._GetVATRate: TVATRate;
begin
  Result := TVATRate(M_VATRate.BoldObject);
  if (assigned(Result) and not (Result is TVATRate)) then
    Assert(false, SysUtils.format(BoldMemberAssertInvalidObjectType, [ClassName, 'VATRate', Result.ClassName, 'TVATRate']));
end;

procedure TInvoiceItem._SetVATRate(const value: TVATRate);
begin
  M_VATRate.BoldObject := value;
end;

procedure TInvoiceItemList.Add(NewObject: TInvoiceItem);
begin
  if Assigned(NewObject) then
    AddElement(NewObject);
end;

function TInvoiceItemList.IndexOf(anObject: TInvoiceItem): Integer;
begin
  result := IndexOfElement(anObject);
end;

function TInvoiceItemList.Includes(anObject: TInvoiceItem) : Boolean;
begin
  result := IncludesElement(anObject);
end;

function TInvoiceItemList.AddNew: TInvoiceItem;
begin
  result := TInvoiceItem(InternalAddNew);
end;

procedure TInvoiceItemList.Insert(index: Integer; NewObject: TInvoiceItem);
begin
  if assigned(NewObject) then
    InsertElement(index, NewObject);
end;

function TInvoiceItemList.GetBoldObject(index: Integer): TInvoiceItem;
begin
  result := TInvoiceItem(GetElement(index));
end;

procedure TInvoiceItemList.SetBoldObject(index: Integer; NewObject: TInvoiceItem);
begin;
  SetElement(index, NewObject);
end;

{$IFDEF UseBoldListEnumerator}
function TInvoiceItemList.GetEnumerator: TInvoiceItemListEnumerator;
begin
 Result := TInvoiceItemListEnumerator.Create(Self);
end;

function TInvoiceItemListEnumerator.GetCurrent: TInvoiceItem;
begin
 Result := List[Index] as TInvoiceItem;
end;

{$ENDIF UseBoldListEnumerator}

function GeneratedCodeCRC: String;
begin
  result := '';
end;

procedure InstallObjectListClasses(BoldObjectListClasses: TBoldGeneratedClassList);
begin
  BoldObjectListClasses.AddObjectEntry('InvoiceClassesRoot', TInvoiceClassesRootList);
  BoldObjectListClasses.AddObjectEntry('Customer', TCustomerList);
  BoldObjectListClasses.AddObjectEntry('Company', TCompanyList);
  BoldObjectListClasses.AddObjectEntry('PrivatePerson', TPrivatePersonList);
  BoldObjectListClasses.AddObjectEntry('VATRate', TVATRateList);
  BoldObjectListClasses.AddObjectEntry('Invoice', TInvoiceList);
  BoldObjectListClasses.AddObjectEntry('InvoiceItem', TInvoiceItemList);
end;

procedure InstallBusinessClasses(BoldObjectClasses: TBoldGeneratedClassList);
begin
  BoldObjectClasses.AddObjectEntry('InvoiceClassesRoot', TInvoiceClassesRoot);
  BoldObjectClasses.AddObjectEntry('Customer', TCustomer);
  BoldObjectClasses.AddObjectEntry('Company', TCompany);
  BoldObjectClasses.AddObjectEntry('PrivatePerson', TPrivatePerson);
  BoldObjectClasses.AddObjectEntry('VATRate', TVATRate);
  BoldObjectClasses.AddObjectEntry('Invoice', TInvoice);
  BoldObjectClasses.AddObjectEntry('InvoiceItem', TInvoiceItem);
end;

var
  CodeDescriptor: TBoldGeneratedCodeDescriptor;

initialization
  CodeDescriptor := GeneratedCodes.AddGeneratedCodeDescriptorWithFunc('InvoiceModel', InstallBusinessClasses, InstallObjectListClasses, GeneratedCodeCRC);
finalization
  GeneratedCodes.Remove(CodeDescriptor);
end.
