(*****************************************)
(*      This file is autogenerated       *)
(*   Any manual changes will be LOST!    *)
(*****************************************)
(* Generated 07.03.2026 12:00:00         *)
(*****************************************)
(* This file should be stored in the     *)
(* same directory as the form/datamodule *)
(* with the corresponding model          *)
(*****************************************)
(* Copyright notice:                     *)
(*                                       *)
(*****************************************)

unit InvoiceClasses;

{$INCLUDE Bold.inc}
{$DEFINE InvoiceClasses_unitheader}
{$INCLUDE InvoiceClasses_Interface.inc}

const
  BoldMemberAssertInvalidObjectType: string = 'Object of singlelink (%s.%s) is of wrong type (is %s, should be %s)';

{ TInvoiceClassesRoot }

procedure TInvoiceClassesRootList.Add(NewObject: TInvoiceClassesRoot);
begin
  if Assigned(NewObject) then
    AddElement(NewObject);
end;

function TInvoiceClassesRootList.IndexOf(anObject: TInvoiceClassesRoot): Integer;
begin
  result := IndexOfElement(anObject);
end;

function TInvoiceClassesRootList.Includes(anObject: TInvoiceClassesRoot) : Boolean;
begin
  result := IncludesElement(anObject);
end;

function TInvoiceClassesRootList.AddNew: TInvoiceClassesRoot;
begin
  result := TInvoiceClassesRoot(InternalAddNew);
end;

procedure TInvoiceClassesRootList.Insert(index: Integer; NewObject: TInvoiceClassesRoot);
begin
  if assigned(NewObject) then
    InsertElement(index, NewObject);
end;

function TInvoiceClassesRootList.GetBoldObject(index: Integer): TInvoiceClassesRoot;
begin
  result := TInvoiceClassesRoot(GetElement(index));
end;

procedure TInvoiceClassesRootList.SetBoldObject(index: Integer; NewObject: TInvoiceClassesRoot);
begin;
  SetElement(index, NewObject);
end;

{$IFDEF UseBoldListEnumerator}
function TInvoiceClassesRootList.GetEnumerator: TInvoiceClassesRootListEnumerator;
begin
 Result := TInvoiceClassesRootListEnumerator.Create(Self);
end;

function TInvoiceClassesRootListEnumerator.GetCurrent: TInvoiceClassesRoot;
begin
 Result := List[Index] as TInvoiceClassesRoot;
end;

{$ENDIF UseBoldListEnumerator}

{ TCustomer }

function TCustomer._Get_M_Name: TBAString;
begin
  assert(ValidateMember('TCustomer', 'Name', 0, TBAString));
  Result := TBAString(BoldMembers[0]);
end;

function TCustomer._GetName: String;
begin
  Result := M_Name.AsString;
end;

procedure TCustomer._SetName(const NewValue: String);
begin
  M_Name.AsString := NewValue;
end;

function TCustomer._Get_M_Address: TBAString;
begin
  assert(ValidateMember('TCustomer', 'Address', 1, TBAString));
  Result := TBAString(BoldMembers[1]);
end;

function TCustomer._GetAddress: String;
begin
  Result := M_Address.AsString;
end;

procedure TCustomer._SetAddress(const NewValue: String);
begin
  M_Address.AsString := NewValue;
end;

function TCustomer._Get_M_City: TBAString;
begin
  assert(ValidateMember('TCustomer', 'City', 2, TBAString));
  Result := TBAString(BoldMembers[2]);
end;

function TCustomer._GetCity: String;
begin
  Result := M_City.AsString;
end;

procedure TCustomer._SetCity(const NewValue: String);
begin
  M_City.AsString := NewValue;
end;

function TCustomer._Get_M_Phone: TBAString;
begin
  assert(ValidateMember('TCustomer', 'Phone', 3, TBAString));
  Result := TBAString(BoldMembers[3]);
end;

function TCustomer._GetPhone: String;
begin
  Result := M_Phone.AsString;
end;

procedure TCustomer._SetPhone(const NewValue: String);
begin
  M_Phone.AsString := NewValue;
end;

function TCustomer._Get_M_Email: TBAString;
begin
  assert(ValidateMember('TCustomer', 'Email', 4, TBAString));
  Result := TBAString(BoldMembers[4]);
end;

function TCustomer._GetEmail: String;
begin
  Result := M_Email.AsString;
end;

procedure TCustomer._SetEmail(const NewValue: String);
begin
  M_Email.AsString := NewValue;
end;

function TCustomer._GetInvoices: TInvoiceList;
begin
  assert(ValidateMember('TCustomer', 'Invoices', 5, TInvoiceList));
  Result := TInvoiceList(BoldMembers[5]);
end;

procedure TCustomerList.Add(NewObject: TCustomer);
begin
  if Assigned(NewObject) then
    AddElement(NewObject);
end;

function TCustomerList.IndexOf(anObject: TCustomer): Integer;
begin
  result := IndexOfElement(anObject);
end;

function TCustomerList.Includes(anObject: TCustomer) : Boolean;
begin
  result := IncludesElement(anObject);
end;

function TCustomerList.AddNew: TCustomer;
begin
  result := TCustomer(InternalAddNew);
end;

procedure TCustomerList.Insert(index: Integer; NewObject: TCustomer);
begin
  if assigned(NewObject) then
    InsertElement(index, NewObject);
end;

function TCustomerList.GetBoldObject(index: Integer): TCustomer;
begin
  result := TCustomer(GetElement(index));
end;

procedure TCustomerList.SetBoldObject(index: Integer; NewObject: TCustomer);
begin;
  SetElement(index, NewObject);
end;

{$IFDEF UseBoldListEnumerator}
function TCustomerList.GetEnumerator: TCustomerListEnumerator;
begin
 Result := TCustomerListEnumerator.Create(Self);
end;

function TCustomerListEnumerator.GetCurrent: TCustomer;
begin
 Result := List[Index] as TCustomer;
end;

{$ENDIF UseBoldListEnumerator}

{ TInvoice }

function TInvoice._Get_M_InvoiceNumber: TBAInteger;
begin
  assert(ValidateMember('TInvoice', 'InvoiceNumber', 0, TBAInteger));
  Result := TBAInteger(BoldMembers[0]);
end;

function TInvoice._GetInvoiceNumber: Integer;
begin
  Result := M_InvoiceNumber.AsInteger;
end;

procedure TInvoice._SetInvoiceNumber(const NewValue: Integer);
begin
  M_InvoiceNumber.AsInteger := NewValue;
end;

function TInvoice._Get_M_InvoiceDate: TBADate;
begin
  assert(ValidateMember('TInvoice', 'InvoiceDate', 1, TBADate));
  Result := TBADate(BoldMembers[1]);
end;

function TInvoice._GetInvoiceDate: TDate;
begin
  Result := M_InvoiceDate.AsDate;
end;

procedure TInvoice._SetInvoiceDate(const NewValue: TDate);
begin
  M_InvoiceDate.AsDate := NewValue;
end;

function TInvoice._Get_M_DueDate: TBADate;
begin
  assert(ValidateMember('TInvoice', 'DueDate', 2, TBADate));
  Result := TBADate(BoldMembers[2]);
end;

function TInvoice._GetDueDate: TDate;
begin
  Result := M_DueDate.AsDate;
end;

procedure TInvoice._SetDueDate(const NewValue: TDate);
begin
  M_DueDate.AsDate := NewValue;
end;

function TInvoice._Get_M_IsPaid: TBABoolean;
begin
  assert(ValidateMember('TInvoice', 'IsPaid', 3, TBABoolean));
  Result := TBABoolean(BoldMembers[3]);
end;

function TInvoice._GetIsPaid: Boolean;
begin
  Result := M_IsPaid.AsBoolean;
end;

procedure TInvoice._SetIsPaid(const NewValue: Boolean);
begin
  M_IsPaid.AsBoolean := NewValue;
end;

function TInvoice._Get_M_TotalAmount: TBACurrency;
begin
  assert(ValidateMember('TInvoice', 'TotalAmount', 4, TBACurrency));
  Result := TBACurrency(BoldMembers[4]);
end;

function TInvoice._GetTotalAmount: Currency;
begin
  Result := M_TotalAmount.AsCurrency;
end;

function TInvoice._Get_M_Customer: TBoldObjectReference;
begin
  assert(ValidateMember('TInvoice', 'Customer', 5, TBoldObjectReference));
  Result := TBoldObjectReference(BoldMembers[5]);
end;

function TInvoice._GetCustomer: TCustomer;
begin
  Result := TCustomer(M_Customer.BoldObject);
  if (assigned(Result) and not (Result is TCustomer)) then
    Assert(false, SysUtils.format(BoldMemberAssertInvalidObjectType, [ClassName, 'Customer', Result.ClassName, 'TCustomer']));
end;

procedure TInvoice._SetCustomer(const value: TCustomer);
begin
  M_Customer.BoldObject := value;
end;

function TInvoice._GetItems: TInvoiceItemList;
begin
  assert(ValidateMember('TInvoice', 'Items', 6, TInvoiceItemList));
  Result := TInvoiceItemList(BoldMembers[6]);
end;

procedure TInvoiceList.Add(NewObject: TInvoice);
begin
  if Assigned(NewObject) then
    AddElement(NewObject);
end;

function TInvoiceList.IndexOf(anObject: TInvoice): Integer;
begin
  result := IndexOfElement(anObject);
end;

function TInvoiceList.Includes(anObject: TInvoice) : Boolean;
begin
  result := IncludesElement(anObject);
end;

function TInvoiceList.AddNew: TInvoice;
begin
  result := TInvoice(InternalAddNew);
end;

procedure TInvoiceList.Insert(index: Integer; NewObject: TInvoice);
begin
  if assigned(NewObject) then
    InsertElement(index, NewObject);
end;

function TInvoiceList.GetBoldObject(index: Integer): TInvoice;
begin
  result := TInvoice(GetElement(index));
end;

procedure TInvoiceList.SetBoldObject(index: Integer; NewObject: TInvoice);
begin;
  SetElement(index, NewObject);
end;

{$IFDEF UseBoldListEnumerator}
function TInvoiceList.GetEnumerator: TInvoiceListEnumerator;
begin
 Result := TInvoiceListEnumerator.Create(Self);
end;

function TInvoiceListEnumerator.GetCurrent: TInvoice;
begin
 Result := List[Index] as TInvoice;
end;

{$ENDIF UseBoldListEnumerator}

{ TInvoiceItem }

function TInvoiceItem._Get_M_Description: TBAString;
begin
  assert(ValidateMember('TInvoiceItem', 'Description', 0, TBAString));
  Result := TBAString(BoldMembers[0]);
end;

function TInvoiceItem._GetDescription: String;
begin
  Result := M_Description.AsString;
end;

procedure TInvoiceItem._SetDescription(const NewValue: String);
begin
  M_Description.AsString := NewValue;
end;

function TInvoiceItem._Get_M_Quantity: TBAInteger;
begin
  assert(ValidateMember('TInvoiceItem', 'Quantity', 1, TBAInteger));
  Result := TBAInteger(BoldMembers[1]);
end;

function TInvoiceItem._GetQuantity: Integer;
begin
  Result := M_Quantity.AsInteger;
end;

procedure TInvoiceItem._SetQuantity(const NewValue: Integer);
begin
  M_Quantity.AsInteger := NewValue;
end;

function TInvoiceItem._Get_M_UnitPrice: TBACurrency;
begin
  assert(ValidateMember('TInvoiceItem', 'UnitPrice', 2, TBACurrency));
  Result := TBACurrency(BoldMembers[2]);
end;

function TInvoiceItem._GetUnitPrice: Currency;
begin
  Result := M_UnitPrice.AsCurrency;
end;

procedure TInvoiceItem._SetUnitPrice(const NewValue: Currency);
begin
  M_UnitPrice.AsCurrency := NewValue;
end;

function TInvoiceItem._Get_M_LineTotal: TBACurrency;
begin
  assert(ValidateMember('TInvoiceItem', 'LineTotal', 3, TBACurrency));
  Result := TBACurrency(BoldMembers[3]);
end;

function TInvoiceItem._GetLineTotal: Currency;
begin
  Result := M_LineTotal.AsCurrency;
end;

function TInvoiceItem._Get_M_Invoice: TBoldObjectReference;
begin
  assert(ValidateMember('TInvoiceItem', 'Invoice', 4, TBoldObjectReference));
  Result := TBoldObjectReference(BoldMembers[4]);
end;

function TInvoiceItem._GetInvoice: TInvoice;
begin
  Result := TInvoice(M_Invoice.BoldObject);
  if (assigned(Result) and not (Result is TInvoice)) then
    Assert(false, SysUtils.format(BoldMemberAssertInvalidObjectType, [ClassName, 'Invoice', Result.ClassName, 'TInvoice']));
end;

procedure TInvoiceItem._SetInvoice(const value: TInvoice);
begin
  M_Invoice.BoldObject := value;
end;

procedure TInvoiceItemList.Add(NewObject: TInvoiceItem);
begin
  if Assigned(NewObject) then
    AddElement(NewObject);
end;

function TInvoiceItemList.IndexOf(anObject: TInvoiceItem): Integer;
begin
  result := IndexOfElement(anObject);
end;

function TInvoiceItemList.Includes(anObject: TInvoiceItem) : Boolean;
begin
  result := IncludesElement(anObject);
end;

function TInvoiceItemList.AddNew: TInvoiceItem;
begin
  result := TInvoiceItem(InternalAddNew);
end;

procedure TInvoiceItemList.Insert(index: Integer; NewObject: TInvoiceItem);
begin
  if assigned(NewObject) then
    InsertElement(index, NewObject);
end;

function TInvoiceItemList.GetBoldObject(index: Integer): TInvoiceItem;
begin
  result := TInvoiceItem(GetElement(index));
end;

procedure TInvoiceItemList.SetBoldObject(index: Integer; NewObject: TInvoiceItem);
begin;
  SetElement(index, NewObject);
end;

{$IFDEF UseBoldListEnumerator}
function TInvoiceItemList.GetEnumerator: TInvoiceItemListEnumerator;
begin
 Result := TInvoiceItemListEnumerator.Create(Self);
end;

function TInvoiceItemListEnumerator.GetCurrent: TInvoiceItem;
begin
 Result := List[Index] as TInvoiceItem;
end;

{$ENDIF UseBoldListEnumerator}

function GeneratedCodeCRC: String;
begin
  result := '';
end;

procedure InstallObjectListClasses(BoldObjectListClasses: TBoldGeneratedClassList);
begin
  BoldObjectListClasses.AddObjectEntry('InvoiceClassesRoot', TInvoiceClassesRootList);
  BoldObjectListClasses.AddObjectEntry('Customer', TCustomerList);
  BoldObjectListClasses.AddObjectEntry('Invoice', TInvoiceList);
  BoldObjectListClasses.AddObjectEntry('InvoiceItem', TInvoiceItemList);
end;

procedure InstallBusinessClasses(BoldObjectClasses: TBoldGeneratedClassList);
begin
  BoldObjectClasses.AddObjectEntry('InvoiceClassesRoot', TInvoiceClassesRoot);
  BoldObjectClasses.AddObjectEntry('Customer', TCustomer);
  BoldObjectClasses.AddObjectEntry('Invoice', TInvoice);
  BoldObjectClasses.AddObjectEntry('InvoiceItem', TInvoiceItem);
end;

var
  CodeDescriptor: TBoldGeneratedCodeDescriptor;

initialization
  CodeDescriptor := GeneratedCodes.AddGeneratedCodeDescriptorWithFunc('InvoiceModel', InstallBusinessClasses, InstallObjectListClasses, GeneratedCodeCRC);
finalization
  GeneratedCodes.Remove(CodeDescriptor);
end.
